### ISSUE TITLE
`vpn-policy-routing` OpenVPN instructions confusion/contradictions?

### ISSUE THREAD

**Issue by posita** [stangri/repo.openwrt.melmac.net#14]
[**Basic OpenVPN Client Config**](https://docs.openwrt.melmac.net/vpn-policy-routing/#basic-openvpn-client-config) indicates that one should create this interface:

```
config interface 'vpnc'
  option proto 'none'
  option ifname 'ovpnc0'
```

This seems to conflict with the earlier instructions in [**Local OpenVPN Server + OpenVPN Client (Scenario 1)**](https://docs.openwrt.melmac.net/vpn-policy-routing/#local-openvpn-server--openvpn-client-scenario-1):

```
config interface 'vpnclient'
  option proto 'none'
  option ifname 'ovpnc0'
```

Are those interfaces meant to be the same (or solve similar problems)? Are their names different for a reason? Those two sections can't be combined, correct? (Meaning they are mutually exclusive?) The docs aren't quite clear on this point.

**Comment by stangri** [comment]
The basic setup and advanced setup are mutually exclusive. However I agree it's better for consistency to have the same section names throughout README, so it's been changed in https://github.com/stangri/docs.openwrt.melmac.net/commit/eb01481086f022c254135f9e531a8625cdbd0a39.

**Comment by posita** [comment]
Thanks!
