### ISSUE TITLE
`vpn-policy-routing`'s "Word about Default Routing" is confusing

### ISSUE THREAD

**Issue by posita** [stangri/repo.openwrt.melmac.net#15]
[**A Word About Default Routing**](https://docs.openwrt.melmac.net/vpn-policy-routing/#a-word-about-default-routing) reads:

> Service does not alter the default routing. Depending on your VPN tunnel settings (and settings of the VPN server you are connecting to), the default routing might be set to go via WAN or via VPN tunnel. This service affects only routing of the traffic matching the policies. If you want to override default routing, follow the instructions below.
>
> [followed by instructions]

What does any of this mean? It sounds like the default routing could be either WAN or VPN. What does "override [the] default routing" mean in this context? Swap? Do something else? It's unclear from the instructions that follow.

I _**think**_ what this means to say is that _**if**_ the default routing is to the VPN and _**not**_ WAN, something like `pull-filter ignore "redirect-gateway"` can make it so that not all traffic goes through the VPN. It's unclear how that setting would help with the opposite (i.e., where the default was WAN).

**Comment by stangri** [comment]
Resolved by https://github.com/stangri/docs.openwrt.melmac.net/commit/0112ba05c2cd7404910cd4c4056ff6fd254c55fa and a lot of references to "Default routing" throughout the document.

**Comment by posita** [comment]
That's much clearer. Thanks!
