### ISSUE TITLE
Public key to verify the package signatures?

### ISSUE THREAD

**Issue by kouhj** [stangri/repo.openwrt.melmac.net#16]
The pre-built repo is very nice! But where is the key-build.pub that could be used to verify the package signatures?

**Comment by stangri** [comment]
[The instructions on how to add the repo](https://docs.openwrt.melmac.net/) contain the public key/instructions on how to add it to an OpenWrt system.

**Comment by kouhj** [comment]
Sorry I was looking around for a URL and overlooked the echo.
