### ISSUE TITLE
 Malformed package file luci-app-pbr_0.9.9-9_all.ipk

### ISSUE THREAD

**Issue by spm1001** [stangri/repo.openwrt.melmac.net#17]
Hi - really excited to try pbr

I followed the instructions [here](https://docs.openwrt.melmac.net) but `opkg update` gives 
```
Downloading https://cdn.jsdelivr.net/gh/stangri/repo.openwrt.melmac.net/Packages.sig
Premature end of file
Signature check failed.
```

Tried to `wget` the [ipk](https://github.com/stangri/repo.openwrt.melmac.net/blob/master/luci-app-pbr_0.9.9-9_all.ipk) to do a manual `opkg install` which gives

```
opkg install luci-app-pbr_0.9.9-9_all.ipk 
Collected errors:
 * pkg_init_from_file: Malformed package file luci-app-pbr_0.9.9-9_all.ipk.
```

Sorry if it's something obvious and not related to the source file - I don't really understand opkg that well. Thought it might have something to do with the recent update to pbr but I get the same with the `luci-app-https-dns-proxy_2022-10-15-6_all.ipk`

**Comment by stangri** [comment]
What are you device and OpenWrt version and where did you download OpenWrt from?

**Comment by spm1001** [comment]
sorry I should have said

- x86 PC with 3 NICs
- OpenWrt 22.03.2 downloaded from [here](https://downloads.openwrt.org/releases/22.03.2/targets/x86/64/)

```
# ubus -S call system board
{"kernel":"5.10.146","hostname":"A_A_x86","system":"Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz","model":"ASUSTeK COMPUTER INC. P8H61-I LX","board_name":"asustek-computer-inc-p8h61-i-lx","rootfs_type":"squashfs","release":{"distribution":"OpenWrt","version":"22.03.2","revision":"r19803-9a599fee93","target":"x86/64","description":"OpenWrt 22.03.2 r19803-9a599fee93"}}
```
I tried downloading from GitHub directly and `scp`ing the ipk - which then has a very different length in both cases. So perhaps `wget` was doing something to the file? 

Now I get

```
# opkg install luci-app-pbr_0.9.9-9_all.ipk 
Unknown package 'luci-app-pbr'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency pbr for luci-app-pbr
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-pbr found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-pbr.
```

which is more useful perhaps - but odd as the control file in the ipk has `Architecture: all`?

**Comment by stangri** [comment]
Can you try deleting my repo from `/etc/opkg/customfeeds.conf` and re-adding it with github as a source: https://docs.openwrt.melmac.net/#add-repository-github ?

When installing from local file, do not forget to indicate the directory, ie: `opkg install ./luci-app-pbr_0.9.9-9_all.ipk`.

**Comment by spm1001** [comment]
Solved! Brilliant - thank you. The signature check worked this time, so I could just do `opkg install luci-app-pbr` not sure what was wrong before. Now to figure out how to use it. Thank you btw - your OpenWRT packages are super thoughtful with nice touches like the automatic redirection of port 53 in https-dns-proxy.
