### ISSUE TITLE
Service Status [ Running | Stopped ] - Command required for the status

### ISSUE THREAD

**Issue by B0F1B0** [stangri/repo.openwrt.melmac.net#23]
I need a command to get Service Status [ Running | Stopped ]. 

![Policy Based Routing - Status - Service Status - Running](https://github.com/stangri/repo.openwrt.melmac.net/assets/39368417/21f7b11b-8650-4808-90ac-d7271bdf4d34)

![Policy Based Routing - Status - Service Status - Stopped](https://github.com/stangri/repo.openwrt.melmac.net/assets/39368417/906d8183-5641-41de-9a09-f68b44d5039c)

Under unknown circumstances, PBR stops working and the service stops. For a script I need the command to query the service status [Running or Stopped]. 

If i run the command `service pbr status | grep stopped`  when PBR has stopped, it return nothing. 
Also the command `service pbr running` return nothing. 

Please tell me which command is used to query the current status (Running or Stopped). 🙂

**Comment by stangri** [comment]
1. You're running a very old version, I'd recommend switching to a latest version in my repo and enabling nft_file_mode option.
2. With the latest version you can do:
   ```sh
   . /etc/init.d/pbr
   is_running && echo "running" || echo "stopped"
  ```

**Comment by B0F1B0** [comment]
> 1. You're running a very old version, I'd recommend switching to a latest version in my repo and enabling nft_file_mode option.
> 2. With the latest version you can do:
>    ```shell
>    . /etc/init.d/pbr
>    is_running && echo "running" || echo "stopped"
>    ```

Thanks for your reply 🙂

1. I am running the latest Version from your repo and nft_file_mode is also enabled: **Version 1.1.5-1 - Running (fw4 nft file mode).** 
2. Thanks for the command. But in my case i will use: 
```shell
. /etc/init.d/pbr
is_running_nft && echo "running" || echo "stopped"
```

**Comment by stangri** [comment]
> 1. I am running the latest Version from your repo and nft_file_mode is also enabled: **Version 1.1.5-1 - Running (fw4 nft file mode).**

Sorry, didn't see the version correctly with my bleary eyes.

> * Thanks for the command. But in my case i will use:

I'd recommend you use the command I posted.
